version: '2'
services:
  jhipstersampleapplicationtest-app:
    image: jhipstersampleapplicationtest
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:mysql://jhipstersampleapplicationtest-mysql:3306/jhipstersampleapplicationtest?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC&createDatabaseIfNotExist=true
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 8080:8080
  jhipstersampleapplicationtest-mysql:
    extends:
      file: mysql.yml
      service: jhipstersampleapplicationtest-mysql
